const animHTML = document.querySelector(".html");
const animCSS = document.querySelector(".css");
const animJAVASCRIPT = document.querySelector(".javascript");
const animJQUERY = document.querySelector(".jquery");
const animPHP = document.querySelector(".php");
const animSQL = document.querySelector(".sql");
const animJAVA = document.querySelector(".java");
const animPYTHON = document.querySelector(".python");
const animCPLUSPLUS = document.querySelector(".cPlusPlus");
const animCSHARP = document.querySelector(".cSharp");
const animXD = document.querySelector(".xd");
const animILLUSTRATOR = document.querySelector(".illustrator");
const animPHOTOSHOP = document.querySelector(".photoshop");
const animANIMATE = document.querySelector(".animate");
const animPREMIER = document.querySelector(".premier");
const animEXCEL = document.querySelector(".excel");
const animPOWERPOINT = document.querySelector(".powerpoint");
const animWORD = document.querySelector(".word");
const animTABLEAU = document.querySelector(".tableau");
const animUIPATH = document.querySelector(".uipath");
const animINVENTOR = document.querySelector(".inventor");
const animDAVINCI = document.querySelector(".davinci");

animHTML.classList.remove("html");
animCSS.classList.remove("css");
animJAVASCRIPT.classList.remove("javascript");
animJQUERY.classList.remove("jquery");
animPHP.classList.remove("php");
animSQL.classList.remove("sql");
animJAVA.classList.remove("java");
animPYTHON.classList.remove("python");
animCPLUSPLUS.classList.remove("cPlusPlus");
animCSHARP.classList.remove("cSharp");
animXD.classList.remove("xd");
animILLUSTRATOR.classList.remove("illustrator");
animPHOTOSHOP.classList.remove("photoshop");
animANIMATE.classList.remove("animate");
animPREMIER.classList.remove("premier");
animEXCEL.classList.remove("excel");
animPOWERPOINT.classList.remove("powerpoint");
animWORD.classList.remove("word");
animTABLEAU.classList.remove("tableau");
animUIPATH.classList.remove("uipath");
animINVENTOR.classList.remove("inventor");
animDAVINCI.classList.remove("davinci");

const observer = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      animHTML.classList.add("html");
      animCSS.classList.add("css");
      animJAVASCRIPT.classList.add("javascript");
      animJQUERY.classList.add("jquery");
      animPHP.classList.add("php");
      animSQL.classList.add("sql");
      animJAVA.classList.add("java");
      animPYTHON.classList.add("python");
      animCPLUSPLUS.classList.add("cPlusPlus");
      animCSHARP.classList.add("cSharp");
      animXD.classList.add("xd");
      animILLUSTRATOR.classList.add("illustrator");
      animPHOTOSHOP.classList.add("photoshop");
      animANIMATE.classList.add("animate");
      animPREMIER.classList.add("premier");
      animEXCEL.classList.add("excel");
      animPOWERPOINT.classList.add("powerpoint");
      animWORD.classList.add("word");
      animTABLEAU.classList.add("tableau");
      animUIPATH.classList.add("uipath");
      animINVENTOR.classList.add("inventor");
      animDAVINCI.classList.add("davinci");
      return;
    }

    animHTML.classList.remove("html");
    animCSS.classList.remove("css");
    animJAVASCRIPT.classList.remove("javascript");
    animJQUERY.classList.remove("jquery");
    animPHP.classList.remove("php");
    animSQL.classList.remove("sql");
    animJAVA.classList.remove("java");
    animPYTHON.classList.remove("python");
    animCPLUSPLUS.classList.remove("cPlusPlus");
    animCSHARP.classList.remove("cSharp");
    animXD.classList.remove("xd");
    animILLUSTRATOR.classList.remove("illustrator");
    animPHOTOSHOP.classList.remove("photoshop");
    animANIMATE.classList.remove("animate");
    animPREMIER.classList.remove("premier");
    animEXCEL.classList.remove("excel");
    animPOWERPOINT.classList.remove("powerpoint");
    animWORD.classList.remove("word");
    animTABLEAU.classList.remove("tableau");
    animUIPATH.classList.remove("uipath");
    animINVENTOR.classList.remove("inventor");
    animDAVINCI.classList.remove("davinci");
  });
});

observer.observe(document.querySelector(".aboutMe-technicalSkills-main"));
